window.app=angular.module("resourceManagerApp",["ui.select2"]).config(function(e,t,r){t.html5Mode(!0),e.when("/Login",{templateUrl:"/Scripts/app/views/login/Login.html"}).when("/Locations",{templateUrl:"/Scripts/app/views/locations/Locations.html",controller:"locationsCtrl"}).when("/About",{templateUrl:"/Scripts/app/views/about/About.html"}).when("/LocationAdd",{templateUrl:"/Scripts/app/views/locations/LocationAdd.html",controller:"locationAddCtrl"}).when("/LocationEdit/:locationId",{templateUrl:"/Scripts/app/views/locations/LocationEdit.html",controller:"locationEditCtrl"}).when("/Resources",{templateUrl:"/Scripts/app/views/resources/Resources.html",controller:"resourcesCtrl"}).when("/ResourceAdd",{templateUrl:"/Scripts/app/views/resources/ResourceAdd.html",controller:"resourceAddCtrl"}).when("/ResourceEdit/:resourceId",{templateUrl:"/Scripts/app/views/resources/ResourceEdit.html",controller:"resourceEditCtrl"}).when("/Resources/:resourceId",{templateUrl:"/Scripts/app/views/resources/ResourceDetails.html",controller:"resourceCtrl"}).when("/Resources/:resourceId/Activities/Add",{templateUrl:"/Scripts/app/views/activities/ResourceActivityAdd.html",controller:"activityAddCtrl"}).when("/Home",{templateUrl:"/Scripts/app/views/home/Home.html",controller:"homeCtrl"}).when("/Error",{templateUrl:"/Scripts/app/views/shared/Error.html"}).otherwise({redirectTo:"/Login"}),r.interceptors.push("authorizationInterceptor")});
window.app=angular.module("resourceManagerApp",["ui.select2"]).config(function(e,t,r){t.html5Mode(!0),e.when("/Login",{templateUrl:"/Scripts/app/views/login/Login.html"}).when("/Locations",{templateUrl:"/Scripts/app/views/locations/Locations.html",controller:"locationsCtrl"}).when("/About",{templateUrl:"/Scripts/app/views/about/About.html"}).when("/LocationAdd",{templateUrl:"/Scripts/app/views/locations/LocationAdd.html",controller:"locationAddCtrl"}).when("/LocationEdit/:locationId",{templateUrl:"/Scripts/app/views/locations/LocationEdit.html",controller:"locationEditCtrl"}).when("/Resources",{templateUrl:"/Scripts/app/views/resources/Resources.html",controller:"resourcesCtrl"}).when("/ResourceAdd",{templateUrl:"/Scripts/app/views/resources/ResourceAdd.html",controller:"resourceAddCtrl"}).when("/ResourceEdit/:resourceId",{templateUrl:"/Scripts/app/views/resources/ResourceEdit.html",controller:"resourceEditCtrl"}).when("/Resources/:resourceId",{templateUrl:"/Scripts/app/views/resources/ResourceDetails.html",controller:"resourceCtrl"}).when("/Resources/:resourceId/Activities/Add",{templateUrl:"/Scripts/app/views/activities/ResourceActivityAdd.html",controller:"activityAddCtrl"}).when("/Home",{templateUrl:"/Scripts/app/views/home/Home.html",controller:"homeCtrl"}).when("/Error",{templateUrl:"/Scripts/app/views/shared/Error.html"}).otherwise({redirectTo:"/Login"}),r.interceptors.push("authorizationInterceptor")}),app.factory("authorizationInterceptor",function(e,t,r){return{responseError:function(o){switch(o.status){case 401:e.$broadcast("logOff"),r.url("/Login");break;case 403:r.url("/Login")}return t.reject(o)}}});
app.factory("authorizationInterceptor",function(r,t,o){return{responseError:function(e){switch(e.status){case 401:r.$broadcast("logOff"),o.url("/Login");break;case 403:o.url("/Login")}return t.reject(e)}}});
app.controller("activitiesCtrl",function(t,i,e,n){t.deleteActivity=function(i){return confirm("Do you want to remove this activity?")&&e.deleteActivity(i).then(function(){e.getActivites(i.ResourceId).then(function(i){t.activities=i},function(t){n.handleError(t)})},function(t){n.handleError(t)}),!1}});
app.controller("activityAddCtrl",function(t,c,r,i,e){t.activity={resourceId:r.resourceId},t.addActivity=function(t){i.addActivity(t).then(function(t){c.url("/Resources/"+t.ResourceId)},function(t){e.handleError(t)})}});
app.controller("homeCtrl",function(n,o){function e(){t()}function t(){o.getTopFileResources().then(function(o){n.resources=o,n.loaded=!0,n.hasContent=o.length>0},function(){})}e()});
app.controller("locationAddCtrl",function(n,o,t,c){n.addLocation=function(n){t.addLocation(n).then(function(){o.url("/Locations")},function(n){c.handleError(n)})}});
app.controller("locationEditCtrl",function(o,n,t,i,c){o.location={},i.getLocation(t.locationId).then(function(n){o.location=n},function(o){c.handleError(o)}),o.editLocation=function(o){i.editLocation(o).then(function(){n.url("/Locations")},function(o){c.handleError(o)})}});
app.controller("locationsCtrl",function(n,o,t,e,i){function c(){l()}function l(){e.getLocations().then(function(o){n.locations=o,n.loaded=!0,n.haveContent=0==o.length},function(n){i.handleError(n)})}n.locations=[],c(),n.deleteLocation=function(n){t.confirm("Do you want to delete this item?")&&e.deleteLocation(n).then(function(){l()},function(n){i.handleError(n)})}});
app.controller("resourceAddCtrl",function(e,o,r,n,c){e.resource={},n.createResourceAddFormModel().then(function(o){e.locations=o},function(){c.handleError()}),e.addResource=function(e){r.addResource(e).then(function(){o.url("/Resources")},function(e){c.handleError(e)})}});
app.controller("resourceCtrl",function(e,r,o,c){e.resource={hasActivites:!1},o.getResource(r.resourceId).then(function(r){e.resource=r,e.loaded=!0},function(e){c.handleError(e)})});
app.controller("resourceEditCtrl",function(e,o,r,n,c,t){e.resource={},e.loading="loading",c.createResourceEditFormModel(r.resourceId).then(function(o){e.locations=o[1],e.resource=o[0],e.loading=""},function(e){t.handleError(e)}),e.editResource=function(e){n.editResource(e).then(function(){o.url("/Resources")},function(e){t.handleError(e)})}});
app.controller("resourcesCtrl",function(e,n,o,t){function r(){u()}function u(){n.getResources().then(function(n){e.resources=n,e.loaded=!0,e.haveContent=0==n.length},function(e){o.handleError(e)})}e.resources=[],e.deleteResource=function(e){t.confirm("Are you sure you want to delete this item?")&&n.deleteResource(e).then(function(){u()},function(e){o.handleError(e)})},r()});
app.controller("resourceMngrCtrl",function(o,i,n){o.loginMode=!0,o.registrationMode=!1,o.loaded=!0,o.login=function(e,t){e.$setValidity("invaliduser",!0),e.$invalid||(o.loaded=!1,n.login(t).then(function(){o.loaded=!0,o.$emit("logOn"),i.url("/Home")},function(){o.loaded=!0,e.$setValidity("invaliduser",!1)}))},o.toggleMode=function(i){"login"===i?(o.loginMode=!0,o.registrationMode=!1):"register"===i&&(o.loginMode=!1,o.registrationMode=!0)},o.register=function(e){return e.password!==e.confirmPassword?void(o.invalidPasswords=!0):(o.loaded=!1,void n.registerUser(e).then(function(){o.loaded=!0,o.$emit("logOn"),i.url("/Home")},function(){}))},o.logOff=function(){n.logOffUser().then(function(){o.$emit("logOff"),o.loginMode=!0,o.registrationMode=!1,i.url("/Login")},function(){})}});
app.directive("resourceActivityList",function(){return{restrict:"E",templateUrl:"/Scripts/app/directives/activities/ResourceActivityList.html",scope:{activities:"=activities"}}});
app.directive("cstDatepicker",function(){return{restrict:"A",require:"ngModel",replace:!0,link:function(e,t,i,n){t.datepicker({maxDate:0,onSelect:function(t){n.$setViewValue(t),e.$apply(),n.$setValidity("invalid",!1)}});t.on("keypress",function(){return!1})}}});
app.directive("cstDelete",function(){return{replace:!0,link:function(e,n){console.log(n),n.on("click",function(){return confirm("Delete item?")})}}});
app.directive("cstModal",function(){return{required:"ngModel",restrict:"A",link:function(n,c,i){c.on("click",function(){var n="#"+i.cstModal;$(n).modal("show")})}}});
﻿app.directive('cstSelect2Dropdown', function () {
    return {
        require: 'ngModel',
        link: function (scope, element, attrs, ngModel) {
            var select = element.select2();
            select.on("change", function (e) {
                alert($(this).select2("val"));
                ngModel.$setViewValue(e.val);
                scope.$apply();
            });
    };
})
app.directive("cstTopMenu",function(){return{restrict:"E",replace:!0,templateUrl:"Scripts/app/partials/TopMenu.html",link:function(t,n){var i=n.find("a");i.on("click",function(){i.removeClass("active"),$(this).addClass("active")}),t.$on("logOff",function(){t.isAuthenticated=!1}),t.$on("logOn",function(){t.isAuthenticated=!0})}}});
app.service("activitySvc",function(e,r,t){return{addUrl:"/api/Resources/@resourceId/Activities/",deleteUrl:"/api/ResourceActivities/",getUrl:"/api/Resources/@resourceId/Activities/",addActivity:function(r){var c=t.defer();return e({method:"post",url:this.addUrl.replace("@resourceId",r.resourceId),data:r}).success(function(e){c.resolve(e)}).error(function(e){c.reject(e)}),c.promise},deleteActivity:function(r){var c=t.defer();return e({method:"delete",url:this.deleteUrl+r.Id}).success(function(e){c.resolve(e)}).error(function(e){c.reject(e)}),c.promise},getActivites:function(r){var c=t.defer();return e({method:"get",url:this.getUrl.replace("@resourceId",r)}).success(function(e){c.resolve(e)}).error(function(e){c.reject(e)}),c.promise}}});
app.factory("locationSvc",function(o,e){return{addLocation:function(t){var r=e.defer();return o({method:"post",url:"/api/Locations",data:t}).success(function(o){r.resolve(o)}).error(function(o){r.reject(o)}),r.promise},editLocation:function(t){var r=e.defer();return o({method:"put",url:"/api/Locations/"+t.Id,data:t}).success(function(o){r.resolve(o)}).error(function(o){r.reject(o)}),r.promise},getLocation:function(t){var r=e.defer();return o({method:"get",url:"/api/Locations/"+t,data:location}).success(function(o){r.resolve(o)}).error(function(o){r.reject(o)}),r.promise}}});
app.factory("locationsSvc",function(e,r){return{url:"/api/Locations/",getLocations:function(){var t=r.defer();return e({method:"get",url:this.url}).success(function(e){t.resolve(e)}).error(function(e){t.reject(e)}),t.promise},deleteLocation:function(t){var o=r.defer();return e({method:"delete",url:this.url+t}).success(function(e){o.resolve(e)}).error(function(e){o.reject(e)}),o.promise}}});
app.factory("resourceSvc",function(e,r){return{url:"/api/Resources/",addResource:function(t){var u=r.defer();return e({method:"post",url:this.url,data:t}).success(function(e){u.resolve(e)}).error(function(e){u.reject(e)}),u.promise},editResource:function(t){var u=r.defer();return e({method:"put",url:this.url+t.Id,data:t}).success(function(e){u.resolve(e)}).error(function(e){u.reject(e)}),u.promise},getResource:function(t){var u=r.defer();return e({method:"get",url:this.url+t}).success(function(e){u.resolve(e)}).error(function(e){u.reject(e)}),u.promise}}});
app.factory("resourcesSvc",function(e,r){return{url:"/api/Resources/",getResources:function(){var t=r.defer();return e({method:"get",url:this.url}).success(function(e){t.resolve(e)}).error(function(e){t.reject(e)}),t.promise},deleteResource:function(t){var o=r.defer();return e({method:"delete",url:this.url+t}).success(function(e){o.resolve(e)}).error(function(e){o.reject(e)}),o.promise},getTopFileResources:function(){var t=r.defer();return e({method:"get",url:this.url+"?count=5"}).success(function(e){t.resolve(e)}).error(function(e){t.reject(e)}),t.promise}}});
app.factory("resourceUtilSvc",function(e,r,t){return{createResourceAddFormModel:function(){var t=e.defer();return r.getLocations().then(function(e){t.resolve(e)}),t.promise},createResourceEditFormModel:function(o){var n=e.all([t.getResource(o),r.getLocations()]);return n.then(function(e){return e}),n}}});
app.service("confirmSvc",function(){return{confirm:function(r){if("string"==typeof r)return confirm(r);throw Error("Invalid type as msg")}}});
app.factory("errorMngrSvc",function(){return{handleError:function(){}}});
app.factory("resourceMngrSvc",function(r,e){return{loginUrl:"/api/Login/",login:function(t){var n=e.defer();return r({method:"put",url:this.loginUrl,data:t}).success(function(r){n.resolve(r)}).error(function(r){n.reject(r)}),n.promise},registerUser:function(t){var n=e.defer();return r({method:"post",url:this.loginUrl,data:t}).success(function(r){n.resolve(r)}).error(function(r){n.reject(r)}),n.promise},checkUserAuthentication:function(){var t=e.defer();return r({method:"get",url:this.loginUrl}).success(function(r){t.resolve(r)}).error(function(r){t.reject(r)}),t.promise},logOffUser:function(){var t=e.defer();return r({method:"put",url:this.loginUrl,data:{Action:1}}).success(function(r){t.resolve(r)}).error(function(r){t.reject(r)}),t.promise}}});